### ISSUE TITLE
What I'm missing so I get undefined method response for nil:NilClass?

### ISSUE THREAD

**Issue by openscript** [graphql-devise/graphql_devise#179]
### Question

First of all, thank you very much for the fantastic Gem and README.md. I feel like I missed something, that's why I'm running into this error:

```
  ↳ app/controllers/graphql_controller.rb:15:in `execute'
undefined method `response' for nil:NilClass
/usr/local/bundle/gems/graphql_devise-0.15.0/lib/graphql_devise/concerns/controller_methods.rb:35:in `response'
/usr/local/bundle/gems/graphql_devise-0.15.0/lib/graphql_devise/concerns/controller_methods.rb:76:in `set_auth_headers'
/usr/local/bundle/gems/graphql_devise-0.15.0/lib/graphql_devise/mutations/login.rb:22:in `resolve'
```

I'm doing the following mutation:

```
mutation SignIn($email: String!, $password: String!) {
  userLogin(email: $email, password: $password) {
    authenticatable {
      email
    }
    credentials {
      accessToken
    }
  }
}
```

The execute method of the `GraphqlController` looks like: 

```
  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      current_user: gql_devise_context(User),
    }
    result = WorkspaceSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue => e
    raise e unless Rails.env.development?
    handle_error_in_development e
  end
```

Also the concern is included:

```
  include GraphqlDevise::Concerns::SetUserByToken
```

Why is ...
```
      def controller
        context[:controller]
      end
```

... returning nil?

**Comment by mcelicalderon** [comment]
Hey @openscript! You need to send the result of `gql_devise_context(User)` directly as the value of your context, not inside the `current_user` key.
```ruby
result = WorkspaceSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
render json: result unless perfomed?
```
Don't forget to check for `performed?`

**Comment by openscript** [comment]
Big thank you to you for the super quick answer! It works :) Do you receive Paypal money on the email address you have in your Github profile? Would love to invite you on a beer or meal.
