### ISSUE TITLE
A class must be provided when mounting a model. String values are no longer supported

### ISSUE THREAD

**Issue by whotwagner** [graphql-devise/graphql_devise#235]
### Describe the bug

I installed graphql_devise and ran the command `bundle exec rails generate graphql_devise:install`. Since that my railsapp crashes with the following error:

```
$ bin/rails server -b 0.0.0.0
WARNING: Zeitwerk defines the constant Generators after the directory

    /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/graphql_devise-1.0.0/lib/generators

To prevent that, please configure the loader to ignore it: 

    loader.ignore("#{__dir__}/generators")

Otherwise, there is a flag to silence this warning:

    Zeitwerk::Loader.for_gem(warn_on_extra_files: false)
=> Booting Puma
=> Rails 6.1.6.1 application starting in development 
=> Run `bin/rails server --help` for more startup options
Exiting
/home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/graphql_devise-1.0.0/lib/graphql_devise/resource_loader.rb:17:in `call': A class must be provided when mounting a model. String values are no longer supported. (GraphqlDevise::InvalidMountOptionsError)
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/graphql_devise-1.0.0/lib/graphql_devise/route_mounter.rb:4:in `mount_graphql_devise_for'
        from /home/ubuntu/Projects/seregen/config/routes.rb:2:in `block in <main>'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:427:in `instance_exec'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:427:in `eval_block'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:409:in `draw'
        from /home/ubuntu/Projects/seregen/config/routes.rb:1:in `<main>'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:47:in `load'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:47:in `block in load_paths'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:47:in `each'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:47:in `load_paths'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:21:in `reload!'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:35:in `block in updater'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/file_update_checker.rb:83:in `execute'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:10:in `execute'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/application/finisher.rb:195:in `block in <module:Finisher>'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:32:in `run'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `each'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `call'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:60:in `run_initializers'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/application.rb:391:in `initialize!'
        from /home/ubuntu/Projects/seregen/config/environment.rb:5:in `<main>'
        from config.ru:3:in `require_relative'
        from config.ru:3:in `block in <main>'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/server.rb:249:in `app'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/server.rb:422:in `wrapped_app'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/commands/server/server_command.rb:37:in `start'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/commands/server/server_command.rb:144:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/commands/server/server_command.rb:135:in `perform'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/command/base.rb:69:in `perform'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/command.rb:48:in `invoke'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/commands.rb:18:in `<main>'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /home/ubuntu/Projects/seregen/bin/rails:5:in `<top (required)>'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
        from <internal:/home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/ubuntu/Projects/seregen/bin/spring:10:in `block in <top (required)>'
        from <internal:kernel>:90:in `tap'
        from /home/ubuntu/Projects/seregen/bin/spring:7:in `<top (required)>'
        from bin/rails:2:in `load'
        from bin/rails:2:in `<main>'

```

### Environment

Gemfile: https://pads.c3w.at/code/#/2/code/view/Q+7cv1IitOQndSxra3JiicQVM1DU8bKZi4IMQIyWyW8/
Gemfile.lock: https://pads.c3w.at/code/#/2/code/view/37xekLSczL-xAJDASM7O0mFrpTIfc0qJDUlFF6rXQzk/

### Steps to reproduce

(Write your steps here:)

1. Add `gem 'graphql_devise'` to Gemfile
2. Run `bundle install`
3. Run `bundle exec rails generate graphql_devise:install`
4. Crash happens when starting the app with `bin/rails --server 0.0.0.0`

### Expected behavior

(Write what you thought would happen.)
Rails starts normally and doesn't crash

### Actual behavior

(Write what happened. Please add stacktraces or http responses!)

```
$ bin/rails server -b 0.0.0.0
WARNING: Zeitwerk defines the constant Generators after the directory

    /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/graphql_devise-1.0.0/lib/generators

To prevent that, please configure the loader to ignore it: 

    loader.ignore("#{__dir__}/generators")

Otherwise, there is a flag to silence this warning:

    Zeitwerk::Loader.for_gem(warn_on_extra_files: false)
=> Booting Puma
=> Rails 6.1.6.1 application starting in development 
=> Run `bin/rails server --help` for more startup options
Exiting
/home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/graphql_devise-1.0.0/lib/graphql_devise/resource_loader.rb:17:in `call': A class must be provided when mounting a model. String values are no longer supported. (GraphqlDevise::InvalidMountOptionsError)
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/graphql_devise-1.0.0/lib/graphql_devise/route_mounter.rb:4:in `mount_graphql_devise_for'
        from /home/ubuntu/Projects/seregen/config/routes.rb:2:in `block in <main>'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:427:in `instance_exec'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:427:in `eval_block'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:409:in `draw'
        from /home/ubuntu/Projects/seregen/config/routes.rb:1:in `<main>'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:47:in `load'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:47:in `block in load_paths'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:47:in `each'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:47:in `load_paths'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:21:in `reload!'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:35:in `block in updater'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/file_update_checker.rb:83:in `execute'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:10:in `execute'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/application/finisher.rb:195:in `block in <module:Finisher>'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:32:in `run'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `each'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `call'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:60:in `run_initializers'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/application.rb:391:in `initialize!'
        from /home/ubuntu/Projects/seregen/config/environment.rb:5:in `<main>'
        from config.ru:3:in `require_relative'
        from config.ru:3:in `block in <main>'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/server.rb:249:in `app'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/rack-2.2.4/lib/rack/server.rb:422:in `wrapped_app'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/commands/server/server_command.rb:37:in `start'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/commands/server/server_command.rb:144:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/commands/server/server_command.rb:135:in `perform'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/command/base.rb:69:in `perform'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/command.rb:48:in `invoke'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/railties-6.1.6.1/lib/rails/commands.rb:18:in `<main>'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /home/ubuntu/Projects/seregen/bin/rails:5:in `<top (required)>'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
        from /home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
        from <internal:/home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/ubuntu/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/ubuntu/Projects/seregen/bin/spring:10:in `block in <top (required)>'
        from <internal:kernel>:90:in `tap'
        from /home/ubuntu/Projects/seregen/bin/spring:7:in `<top (required)>'
        from bin/rails:2:in `load'
        from bin/rails:2:in `<main>'

```

### Reproducible demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by whotwagner** [comment]
I was able to fix this. the generator created the following line in config/routes.rb:

```
mount_graphql_devise_for 'User', at: 'graphql'
```

I changed that to:

```
mount_graphql_devise_for User, at: 'graphql'
```

**Comment by 00dav00** [comment]
Hi @whotwagner  that is a very nice catch!
The generator is still using the class as a string when it would be using the class itself. 

In case you want to create PR this is the [related line](https://github.com/graphql-devise/graphql_devise/blob/master/lib/generators/graphql_devise/install_generator.rb#L41).

Thanks so much for reporting this.

**Comment by whotwagner** [comment]
Do you think that it might be safe to simply remove the comments or do you expect  backwards compatibility issues?
