### ISSUE TITLE
NoMethodError generate_confirmation_token! but not supporting confirmable

### ISSUE THREAD

**Issue by aarona** [graphql-devise/graphql_devise#24]
I'm not using the `confirmable` plugin as you can see here:

**user.rb:**
```
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  include GraphqlDevise::Concerns::Model
end
```

You can also see my **schema.rb** file to see that I'm not supporting it:
```
create_table "users", force: :cascade do |t|
    t.string "provider", default: "email", null: false
    t.string "uid", default: "", null: false
    t.string "name"
    t.string "nickname"
    t.string "image"
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.boolean "allow_password_change", default: false
    t.datetime "remember_created_at"
    t.json "tokens"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
    t.index ["uid", "provider"], name: "index_users_on_uid_and_provider", unique: true
  end
```
 I go to run the following mutation:

```
mutation {
  userSignUp(email:"aaron@example.com", password:"123456", passwordConfirmation:"123456") {
    authenticable {
      id
      email
      name
    }
  }
}
```

The record gets created but then I get the following server error:

```
NoMethodError (undefined method `generate_confirmation_token!' for #<User:0x0000000004c589c0>):
  
activemodel (6.0.0) lib/active_model/attribute_methods.rb:431:in `method_missing'
devise_token_auth (1.1.2) app/models/devise_token_auth/concerns/user.rb:54:in `send_confirmation_instructions'
graphql_devise (0.4.0) app/graphql/graphql_devise/mutations/sign_up.rb:20:in `resolve'
graphql (1.9.14) lib/graphql/schema/resolver.rb:90:in `public_send'
graphql (1.9.14) lib/graphql/schema/resolver.rb:90:in `block (3 levels) in resolve_with_support'
.... (I can give you the full stack if you need it)
puma (3.12.1) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

Looks like the error is caused by calling `resource.send_confirmation_instructions` but that's dependent upon the method `requires_confirmation?` to be true and I don't think it should be in this case.

**Comment by mcelicalderon** [comment]
You are right, pushing a PR to fix that now.

**Comment by aarona** [comment]
>mfw

![](https://pics.me.me/thumb_look-seem-helping-nemegenerator-ier-look-see-im-helping-ralph-52441823.png)
