### ISSUE TITLE
Cannot make it work with Mongoid

### ISSUE THREAD

**Issue by jpmermoz** [graphql-devise/graphql_devise#244]
It looks like graphql-devise is getting some issues while trying to work with Mongoid instead of AR.

It appears that when you try to login using the userLogin mutation, it fails because it is trying to access a property called "connection" for the base class User, but Mongoid does not have that attribute / property.

I looked at what devise_token_auth does in these cases, and I guess that it can be fixed by simply adding an & before trying to call the .connection. (Please look at the find_resource method here: https://github.com/lynndylanhurley/devise_token_auth/blob/ec68e47f2a3e743bd51293369d059508974aed14/app/controllers/devise_token_auth/concerns/resource_finder.rb#L31)

Maybe this can be fixed in a similar way, by running something like:

`resource_class&.connection&.adapter_name&.downcase&.include?('mysql')`

Or just simply testing first:

`resource_class.respond_to?(:connection)`

Line 88:

https://github.com/graphql-devise/graphql_devise/blob/c9011c62f13e0c2838cd4ccbda87ab11742558a4/lib/graphql_devise/concerns/controller_methods.rb#L87

### Describe the bug

I cannot make the gem work with Mongoid. After setting up everything (running rails g devise_token_auth:install_mongoid User auth), I'm getting the following error:

`undefined method connection for User:Class
`

This is happening on the controller_methods.rb file (line 88)
`if resource_class.connection.adapter_name.downcase.include?('mysql')
`
### Environment

https://gist.github.com/jpmermoz/70b5792f3f74718a996a6995ba83d847

### Steps to reproduce

(Write your steps here:)

1. Create a new project using Mongoid instead of AR
2. Add graphql-devise gem
3. Mount schema.
4. Try to login running the mutation

### Expected behavior

Should be able to login by looking the user using Mongo.

### Actual behavior

```

wadio-api-api-1  |   Parameters: {"query"=>"mutation {\n  userLogin(email: \"asd@asd.com\", password: \"123123\") {\n    authenticatable {\n      id\n      email\n    }\n  }\n}", "variables"=>{"startsAt"=>"2022-06-06 00:00:00", "endsAt"=>"2022-06-13 00:00:00"}, "graphql"=>{"query"=>"mutation {\n  userLogin(email: \"asd@asd.com\", password: \"123123\") {\n    authenticatable {\n      id\n      email\n    }\n  }\n}", "variables"=>{"startsAt"=>"2022-06-06 00:00:00", "endsAt"=>"2022-06-13 00:00:00"}}}
wadio-api-api-1  | undefined method `connection' for User:Class
wadio-api-api-1  | 
wadio-api-api-1  |       if resource_class.connection.adapter_name.downcase.include?('mysql')
wadio-api-api-1  |                        ^^^^^^^^^^^
wadio-api-api-1  | Did you mean?  collection
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql_devise-1.1.0/lib/graphql_devise/concerns/controller_methods.rb:88:in `find_resource'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql_devise-1.1.0/lib/graphql_devise/mutations/login.rb:12:in `resolve'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/schema/resolver.rb:105:in `public_send'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/schema/resolver.rb:105:in `block (3 levels) in resolve_with_support'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/schema.rb:1033:in `after_lazy'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/schema/resolver.rb:93:in `block (2 levels) in resolve_with_support'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/schema.rb:1033:in `after_lazy'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/schema/resolver.rb:84:in `block in resolve_with_support'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/schema.rb:1033:in `after_lazy'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/schema/resolver.rb:73:in `resolve_with_support'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/schema/field.rb:686:in `public_send'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/schema/field.rb:686:in `block (2 levels) in resolve'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/schema/field.rb:807:in `with_extensions'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/schema/field.rb:657:in `block in resolve'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/schema.rb:1033:in `after_lazy'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/schema/field.rb:655:in `resolve'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:501:in `block (3 levels) in evaluate_selection_with_args'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/tracing.rb:80:in `call_tracers'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/tracing.rb:82:in `block in call_tracers'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql_devise-1.1.0/lib/graphql_devise/schema_plugin.rb:37:in `trace'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/tracing.rb:82:in `call_tracers'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/tracing.rb:66:in `trace'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:500:in `block (2 levels) in evaluate_selection_with_args'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:828:in `call_method_on_directives'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:497:in `block in evaluate_selection_with_args'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:927:in `after_lazy'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:435:in `evaluate_selection_with_args'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:428:in `block in evaluate_selection'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/schema/member/has_arguments.rb:246:in `block (3 levels) in coerce_arguments'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/dataloader.rb:181:in `block in run'
wadio-api-api-1  | /bundle/vendor/ruby/3.1.0/gems/graphql-2.0.14/lib/graphql/dataloader.rb:303:in `block in spawn_fiber'
```

### Reproducible demo

I'll try to make a demo repo with the fail.

**Comment by 00dav00** [comment]
Hi @jpmermoz ,  thanks for reporting this.

**Comment by jpmermoz** [comment]
So, luckily mongoid-locker was not an issue, but I've found another problem here:

https://github.com/graphql-devise/graphql_devise/blob/c9011c62f13e0c2838cd4ccbda87ab11742558a4/lib/graphql_devise/concerns/additional_model_methods.rb#L8

It appears that the **reconfirmable** method is asking for **column_names** but Mongoid uses **fields**.
I've fixed it on my fork by comparing with both column_names and fields:

https://github.com/jpmermoz/graphql_devise/blob/mongoid/lib/graphql_devise/concerns/additional_model_methods.rb

```
def reconfirmable
        column_names = respond_to?(:column_names) ? column_names : []
        field_names = respond_to?(:fields) ? fields.keys : []
        devise_modules.include?(:confirmable) && (column_names.include?('unconfirmed_email') || field_names.include?('unconfirmed_email'))
      end
```

**Comment by jpmermoz** [comment]
I've created a PR here: #245
