### ISSUE TITLE
NoMethodError: undefined method `case_insensitive_keys' for nil:NilClass

### ISSUE THREAD

**Issue by celsoMartins** [graphql-devise/graphql_devise#268]
Hi.

My mobile app needs to pass some arguments about the phone on the login. We need that because the login can happen from different devices and we need to have the information about each device without asking for a new sign-up.

I've copied the code we can find in the dummy application but it returns the error:

```
NoMethodError:
 undefined method `case_insensitive_keys' for nil:NilClass
# /Users/celsomartins/.rvm/gems/ruby-3.2.2@aposta10/gems/graphql_devise-1.4.0/lib/graphql_devise/concerns/controller_methods.rb:99:in `get_case_insensitive_field'
# /Users/celsomartins/.rvm/gems/ruby-3.2.2@aposta10/gems/graphql_devise-1.4.0/lib/graphql_devise/mutations/login.rb:14:in `resolve'
# ./app/graphql/mutations/login.rb:8:in `resolve'
```

```
module Mutations
  class Login < GraphqlDevise::Mutations::Login
    field :user, Types::UserType, null: true

    def resolve(email:, password:)
      original_payload = super do |user|
        user.do_something
        user.reload
      end

      original_payload.merge(user: original_payload[:authenticatable])
    end
  end
end
```

What am I missing?

I'm adding below the code with the new fields I need.

```
# frozen_string_literal: true

module Mutations
  class Login < GraphqlDevise::Mutations::Login
    argument :device_fabricator, String, required: false
    argument :device_model, String, required: false
    argument :device_push_token, String, required: false
    argument :device_token, String, required: false

    field :user, Types::UserType, null: true

    def resolve(email:, password:, device_fabricator:, device_model:, device_token:, device_push_token:)
      original_payload = super(email: email, password: password) do |user|
        mobile_device = UserMobileDevice.where(device_token: device_token).first_or_initialize

        mobile_device.update(device_fabricator: device_fabricator, device_model: device_model, device_token: device_token, device_push_token: device_push_token) unless mobile_device.persisted?

        user.reload
      end

      original_payload.merge(user: original_payload[:authenticatable])
    end
  end
end
```

Thanks in advance.

**Comment by 00dav00** [comment]
Hi @celsoMartins , how are you using gem? 
Are using the [schema provided](https://github.com/graphql-devise/graphql_devise#mounting-auth-schema-on-a-separate-route) by the engine itself? or are you using it in an [existing schema](https://github.com/graphql-devise/graphql_devise#mounting-operations-in-an-existing-schema)? 
Is it possible for you share a bit more on how are you configuring the gem?

**Comment by celsoMartins** [comment]
Thanks for your prompt answer.

I'm using it in an existing schema.

If I do not override the default behavior, the login feature works well. But now I need those new fields on the login. So I tried the "tracing bullet" by simply copying what you have on your dummy app and testing it. But it didn't work.

```
# frozen_string_literal: true

require 'graphql/batch'

class Aposta10Schema < GraphQL::Schema
  max_complexity 1000
  # Minimum is 13 because of introspection query.
  max_depth 13

  use GraphqlDevise::SchemaPlugin.new(
    query: Types::QueryType,
    mutation: Types::MutationType,
    authenticate_default: false,
    resource_loaders: [
      GraphqlDevise::ResourceLoader.new(User)
    ]
  )

  mutation(Types::MutationType)
  query(Types::QueryType)

  # For batch-loading (see https://graphql-ruby.org/dataloader/overview.html)
  use GraphQL::Dataloader

  # https://github.com/Shopify/graphql-batch
  use GraphQL::Batch

  # GraphQL-Ruby calls this when something goes wrong while running a query:

  # Union and Interface Resolution
  def self.resolve_type(_abstract_type, _obj, _ctx)
    # TODO: Implement this method
    # to return the correct GraphQL object type for `obj`
    raise(GraphQL::RequiredImplementationMissingError)
  end

  # Relay-style Object Identification:

  # Return a string UUID for `object`
  def self.id_from_object(object, type_definition, _query_ctx)
    # For example, use Rails' GlobalID library (https://github.com/rails/globalid):
    object_id = object.to_global_id.to_s
    # Remove this redundant prefix to make IDs shorter:
    object_id = object_id.sub("gid://#{GlobalID.app}/", '')
    encoded_id = Base64.urlsafe_encode64(object_id)
    # Remove the "=" padding
    encoded_id = encoded_id.sub(/=+/, '')
    # Add a type hint
    type_hint = type_definition.graphql_name.first
    "#{type_hint}_#{encoded_id}"
  end

  # Given a string UUID, find the object
  def self.object_from_id(encoded_id_with_hint, _query_ctx)
    # For example, use Rails' GlobalID library (https://github.com/rails/globalid):
    # Split off the type hint
    _type_hint, encoded_id = encoded_id_with_hint.split('_', 2)
    # Decode the ID
    id = Base64.urlsafe_decode64(encoded_id)
    # Rebuild it for Rails then find the object:
    full_global_id = "gid://#{GlobalID.app}/#{id}"
    GlobalID::Locator.locate(full_global_id)
  end
end
```

**Comment by celsoMartins** [comment]
It worked only by adding the operations in the schema. We customized the register as well, and we didn't need to do that, so we assumed the same. 

Thanks a lot.
